app = "fly-proxy-ib7syq"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = []

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
